---
- name: Create systemd file.
  copy:
   dest: "/etc/systemd/system/mozart-server.service"
   content: |
     [Unit]
     Description=Mozart Server
     Documentation=https://github.com/zbblanton/mozart
     [Service]
     ExecStart=/usr/local/bin/mozart-server
     Restart=on-failure
     RestartSec=5
     [Install]
     WantedBy=multi-user.target
- name: Reload systemd
  systemd: daemon_reload=yes
